prometheus:
  url: http://prometheus-server.default.svc.cluster.local
  port: 80

rules:
  custom:
    - seriesQuery: 'active_sessions{namespace!="", pod!=""}' 
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        as: "active_sessions"
      metricsQuery: 'sum(active_sessions) by (<<.GroupBy>>)'


# rules:
#   custom:
#     - seriesQuery: 'active_sessions{namespace!="", pod!=""}' 
#       resources:
#         overrides:
#           namespace: {resource: "namespace"}
#           pod: {resource: "pod"}
#       name:
#         as: "active_sessions"
#       metricsQuery: 'sum(active_sessions) by (kubernetes_pod_name)'