apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-priority-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: low-priority
  template:
    metadata:
      labels:
        app: low-priority
    spec:
      priorityClassName: low-priority # Correct location for priorityClassName
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
        resources:
          requests:
            memory: "300Mi"
            cpu: "300m"
          limits:
            memory: "300Mi"
            cpu: "300m"
