apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-order-app
  labels:
    app: flask-order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-order-app
  template:
    metadata:
      labels:
        app: flask-order-app
    spec:
      containers:
      - name: flask-order-app
        image: dipinthomas2003/flask-order-app:1
        ports:
        - containerPort: 5000
          name: app
        - containerPort: 8000
          name: metrics
        env:
        - name: PROMETHEUS_METRICS_PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-order-service
  labels:
    app: flask-order-app
spec:
  selector:
    app: flask-order-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: app
    name: app
  - protocol: TCP
    name: metrics
    port: 8000
    targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-order-servicemonitor
  labels:
    app: flask-order-app
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: flask-order-app
  endpoints:
  - port: "metrics"
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
