prometheus:
  url: http://prometheus-operated.default.svc.cluster.local
  port: 9090


rules:
  external:
    - seriesQuery: 'order_count{job="flask-order-service"}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
      name:
        matches: "order_count"
      metricsQuery: 'order_count{job="flask-order-service"}'

####
# Leaving this as a back-up , plz ignore this
# pod scaling working per pod
# use the hpa of this coimmit only
####
# # This is a working config for per pod scaling
# rules:
#   external:
#     - seriesQuery: 'order_count{namespace!="",pod!=""}'
#       resources:
#         overrides:
#           namespace:
#             resource: "namespace"
#           pod:
#             resource: "pod"
#       name:
#         matches: "order_count"
#       metricsQuery: 'order_count{namespace="default",job="flask-order-service"}'
#
# you will need below HPA to go with this adaptor configuration
#

#---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: flask-order-hpa
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: flask-order-app
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Pods
#     pods:
#       metric:
#         name: order_count
#       target:
#         type: AverageValue
#         averageValue: "200"  # Set this to your desired threshold per pod