apiVersion: v1
kind: Secret
metadata:
  name: keda-trigger-auth-redis-secret
type: Opaque
data:
  password: amhibm9pdWhramo=
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
spec:
  scaleTargetRef:
    name: nginx
  triggers:
  - type: redis
    metadata:
      address: redis:6379
      listName: mylist
      listLength: "10"
    authenticationRef:
      name: keda-trigger-auth-redis-secret
