apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-prometheus-app
  labels:
    app: flask-prometheus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-prometheus-app
  template:
    metadata:
      labels:
        app: flask-prometheus-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      containers:
      - name: flask-prometheus-app
        image: dipinthomas2003/flask-prometheus-app:1
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask-prometheus-app-service
  labels:
    app: flask-prometheus-app
spec:
  selector:
    app: flask-prometheus-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
