server:
  scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'kubernetes-apiservers'
      kubernetes_sd_configs:
        - role: endpoints
      scheme: https
    - job_name: 'custom-metrics'
      static_configs:
        - targets: ['flask-prometheus-app-service:8000']
