prometheus:
  url: http://prometheus-server.default.svc.cluster.local

rules:
  custom:
    - seriesQuery: 'http_requests_total{namespace!="", pod!=""}' 
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>[5m])) by (<<.GroupBy>>)'