apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-dispatch-app
  name: flask-dispatch-service
spec:
  ports:
  - name: app
    port: 8080
    protocol: TCP
  selector:
    app: flask-dispatch-app
  type: ClusterIP
