apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: rabbitmq
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-08-19T03:07:48Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/version: 3.13.6
    helm.sh/chart: rabbitmq-14.6.6
    release: prometheus-operator   <This is dependent on the prometheus installation>
  name: rabbitmq
  namespace: default
  resourceVersion: "2664173"
  uid: 29707637-c6b0-49e5-8104-ea6243325835
spec:
  endpoints:
  - interval: 30s
    port: metrics
  jobLabel: ""
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: rabbitmq
      app.kubernetes.io/name: rabbitmq