---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-dispatch-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-dispatch-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: order_count
      target:
        type: Value
        averageValue: "350"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0  # No stabilization period for scale-up
      selectPolicy: Max
      policies:
      - type: Pods
        value: 4           # Maximum number of pods to scale up at once
        periodSeconds: 60  # Within 60 seconds
      - type: Percent
        value: 100         # Allow scaling up by 100% (doubling the pods) at once
        periodSeconds: 60  # Within 60 seconds
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      selectPolicy: Max
      policies:
      - type: Pods
        value: 2           # Maximum number of pods to scale down at once
        periodSeconds: 60  # Within 60 seconds
      - type: Percent
        value: 50          # Allow scaling down by 50% at once
        periodSeconds: 60  # Within 60 seconds
