---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: flask-app
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name:  # Student to fill
  updatePolicy:
    updateMode: "Off"
    evictionRequirements:
      - resources: [ -- ]  # student to fill  ["cpu", "memory"]
        changeRequirement: TargetHigherThanRequests
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: ---  # [ student to add 100m or config based on the lab]
          memory: --- # [ student to add 150mi or config based on the lab]
        maxAllowed:
          cpu: --  # [ student to add 1000m or config based on the lab]
          memory: --- # [ student to add 10000mi or config based on the lab]
        controlledResources: [ --]  # student to fill  ["cpu", "memory"]